'use client';

import { useEffect, useRef } from 'react';
import HeroSection from '@/components/HeroSection';
import SocialProof from '@/components/SocialProof';
import HowItWorks from '@/components/HowItWorks';
import ExampleBrands from '@/components/ExampleBrands';
import IndustryCategories from '@/components/IndustryCategories';
import { useRouter } from 'next/navigation';

function useScrollReveal() {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const children = el.querySelectorAll('.reveal');
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('visible');
          }
        });
      },
      { threshold: 0.1, rootMargin: '0px 0px -60px 0px' }
    );

    children.forEach((child) => observer.observe(child));
    return () => observer.disconnect();
  }, []);

  return ref;
}

export default function Home() {
  const scrollRef = useScrollReveal();
  const router = useRouter();

  return (
    <main className="min-h-screen" ref={scrollRef}>
      {/* Hero */}
      <HeroSection />

      {/* Social Proof */}
      <SocialProof />

      {/* How It Works */}
      <section className="py-24 sm:py-32 px-6 md:px-12">
        <div className="max-w-5xl mx-auto reveal">
          <HowItWorks />
        </div>
      </section>

      {/* Example Brands */}
      <section className="py-24 sm:py-32 px-6 md:px-12 border-t border-[var(--border-subtle)]">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16 reveal">
            <p className="text-[12px] uppercase tracking-[0.2em] text-[var(--text-quaternary)] mb-4">
              Examples
            </p>
            <h2 className="text-[28px] sm:text-[40px] font-bold tracking-[-0.03em] text-[var(--text-primary)]">
              See what&apos;s possible
            </h2>
            <p className="mt-3 text-[15px] text-[var(--text-tertiary)] max-w-md mx-auto">
              Real brand kits generated by our AI in under 60 seconds
            </p>
          </div>
          <div className="reveal">
            <ExampleBrands />
          </div>
        </div>
      </section>

      {/* Industry Categories */}
      <div className="reveal border-t border-[var(--border-subtle)]">
        <IndustryCategories />
      </div>

      {/* Final CTA */}
      <section className="py-24 sm:py-32 px-6 text-center border-t border-[var(--border-subtle)]">
        <div className="max-w-xl mx-auto reveal">
          <h2 className="text-[32px] sm:text-[48px] font-bold tracking-[-0.03em] text-[var(--text-primary)] mb-4">
            Ready to build your brand?
          </h2>
          <p className="text-[16px] text-[var(--text-tertiary)] mb-8">
            Join 10,000+ entrepreneurs who launched their brand with BrandSlop
          </p>
          <button
            onClick={() => router.push('/create')}
            className="px-10 py-4 rounded-full bg-[#00D4AA] text-[#08080A] text-[16px] font-bold hover:bg-[#00E4BA] transition-all duration-300 hover:shadow-[0_0_30px_rgba(0,212,170,0.3)] active:scale-[0.97]"
          >
            Create Your Brand →
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[var(--border-subtle)] py-8 px-6">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row justify-between items-center gap-4">
          <p className="text-[13px] font-medium text-[var(--text-quaternary)] tracking-[-0.01em]">
            BrandSlop
          </p>
          <div className="flex gap-8">
            <span className="text-[12px] text-[var(--text-muted)]">AI-powered branding</span>
            <span className="text-[12px] text-[var(--text-muted)]">© 2025</span>
          </div>
        </div>
      </footer>
    </main>
  );
}
